### ISSUE TITLE
Installation - Fix https error on Firefox on unix systems

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#381]
**Describe the bug**
When trying to access a https://*.massa on Firefox I've got the following error message: 
`SEC_ERROR_REUSED_ISSUER_AND_SERIAL`

**To Reproduce**

1. Install and Run Thyra on Innonet 17 (no website on Testnet 18 for now) 
2. Try to access https://flappy.massa on Firefox
3. See the error below
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/109611779/210604365-78d4a981-b3b2-4a83-af1f-4e671fd2c271.png">

**Expected behavior**
https://*.massa should be accessible directly

**Thyra version**
Latest version of the main running on InnoNet 17

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox

**Additional context**
On GoogleChrome, I tested with 2 different websites (flappy.massa & psycho.massa) it works!

**Comment by gregLibert** [comment]
If I had to bet I would bet on the serial number field of the certificate which in the [current code](https://github.com/massalabs/thyra/blob/c9473ca27ef6d784b44d1457f5f432d8bb86d3f0/pkg/certificate/certificate.go#L95) is systematically null.

I think putting a hash of the website name should solve the problem. If it is not enough, we could add the date...

**Comment by SebastienValla** [comment]
serialNumber code changed, mkCert is not compatible with firefox

![image](https://user-images.githubusercontent.com/83454858/210828493-a5549f4c-b308-4127-8935-0b0930a0af55.png)

**Comment by gregLibert** [comment]
> serialNumber code changed, mkCert is not compatible with firefox
> 
> ![image](https://user-images.githubusercontent.com/83454858/210828493-a5549f4c-b308-4127-8935-0b0930a0af55.png)

see this discussion: https://github.com/FiloSottile/mkcert/issues/239

**Comment by SebastienValla** [comment]
It still doesn't work for firefox
options : add a to do to add it manualy in firefox
- change the way we generate certificates

**Comment by Thykof** [comment]
On Ubuntu 22, I cleaned up everything:

```
sudo apt remove massastation
sudo rm -rf /usr/local/share/massastation
sudo rm -rf /etc/massastation
sudo rm -rf /home/nathan_sv_ms/.local/share/mkcert
sudo rm -rf /usr/local/share/ca-certificates/*
```

Then I reinstall with main branch artifacts: https://github.com/massalabs/station/actions/runs/5475290747

During installation I can see that mkcert fail:

```
The local CA is already installed in the system trust store! 👍
ERROR: no Firefox and/or Chrome/Chromium security databases found

Note: the local CA is not installed in the Firefox and/or Chrome/Chromium trust store.
Run "mkcert -install" for certificates to be trusted automatically ⚠️
```

To manually fix the issue:
```
curl -sL https://dl.filippo.io/mkcert/latest\?for\=linux/amd64 -o mkcert
chmod +x ./mkcert
chmod +x ./mkcert
```

output is:
```
Created a new local CA 💥
The local CA is now installed in the system trust store! ⚡️
The local CA is now installed in the Firefox and/or Chrome/Chromium trust store (requires browser restart)! 🦊
```
And then I can navigate on firefox, chrome, opera with HTTPS.

**Comment by Thykof** [comment]
issue on Ubuntu with Chrome: https://station.massa doesn’t work because during installation, mkcert -install doesn’t creates certificates in ~/.local/share/mkcert so our logic implemented in go to install the certificate in the system store and the NSS store fail to load the certificate.

<img width="1378" alt="image" src="https://github.com/massalabs/station/assets/11590067/56306ba1-252f-4020-950f-6c0ad18f254c">

**Comment by Thykof** [comment]
We will fix this by generating a root CA if the one that mkcert should have create is not found (must have for ICO quests milestone).

After that, we will create an issue to remove mkcert from everywhere in the code (should have for ICO quests milestone)

**Comment by Thykof** [comment]
The last PR broke the https for macos Chrome: https://github.com/massalabs/station/issues/1098

**Comment by Thykof** [comment]
QA: we now have ubuntu firefox, ubuntu chrome, macos firefox working thanks to NSS database implementation, macos chrome working thanks to OS store implementation.

QA OK, no regression tested on ubuntu.
